### ISSUE TITLE
Hey I can not find this on the npm store / website 

### ISSUE THREAD

**Issue by Isaak-Marcel** [ekdennisek/tradera-api-client#1]
I can not find the package on the npm website, it would be really nice to use it and get the type safety when making the requests.
 
 Also btw, would I be able to get your email or contact info like LinkedIn, I am working on a new startup where we need to integrate with Tradera, and maybe it would be good to have you on the team or if you could do some sort of consulting thing.

**Comment by ekdennisek** [comment]
Yeah, sorry about that. The whole thing was so unusable in its current state that I pulled it from npm altogether. I've actually been meaning to rewrite it from scratch in the near future. Let me do that, and then we can talk.

**Comment by ekdennisek** [comment]
It's back up at npm now. Bear in mind though, that it's mostly stubs at the moment. Feel free to submit a pull request if there's anything you want that isn't yet implemented.

**Comment by Isaak-Marcel** [comment]
Okay great thank you, I will definitely make a pull request if there is some feature that I need to add
